### ISSUE TITLE
[Question] responsive Grid support

### ISSUE THREAD

**Issue by felixmosh** [catamphetamine/virtual-scroller#16]
Hi,
First of all thank you for adding a support for Grid 🙏🏼

If I've a "responsive" grid, made by `flex` & `flex-wrap`, this means that the browser layout the grid automatically.

What is the best option / your suggestion to support it?

For example consider such layout,

```html
<style>
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  width: 200px;
  flex-basis: 200px;
}
</style>
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  ...
</ul>
```

In each window size the browser will decide how many items "enters" into a "row".

**Comment by catamphetamine** [comment]
> In each window size the browser will decide how many items "enters" into a "row".

I had an idea about automatically measuring the columns count: instead of calling the supplied `getColumnsCount()` function, it would do something like:

```js
function getColumnsCount() {
  const firstRowTopCoordinate = container.childNodes[0].getBoundingClientRect().top
  let i = 0
  while (i < container.childNodes.length) {
    const topCoordinate = container.childNodes[i].getBoundingClientRect().top
    if (topCoordinate !== firstRowTopCoordinate) {
      return i
    }
    i++
  }
}
```

The issue with that approach is that the columns count isn't known before the list has rendered enough items.
And it can't be assumed `1` "by default", because in that case the grid wouldn't get rendered properly: the rendering logic will sum up item heights until its exceeds the screen height, and after that no more items will be rendered. And, if items are tall enough, then the first row will never be rendered initially, because the library will think that the rest of the items are invisible.

So, how should the list know how much items should it render initially to get more than a single row?
It could be a configuration option, but in that case it would mean that the developer should also know the columns count, so they could just supply the `getColumnsCount()` parameter instead.

Therefore, the `<VirtualScroller/>` component doesn't seem to have a way of supporting non-deterministic layouts.

**Comment by felixmosh** [comment]
I need to think regarding it, sounds like the measurement should be done only once at start, with cached calculations. 
(this is what instagram are doing). This approach will not support browser resize, but, it is not a real scenario (users not changing the window width).

Thank you for your response. 🙏🏼

**Comment by catamphetamine** [comment]
> I need to think regarding it

Seems like in your case it would be something simple, like `Math.ceil(scrollableContainer.getWidth() / 200px)`, or something like that.

**Comment by felixmosh** [comment]
Yeah, it will work.
Thanx
