### ISSUE TITLE
[Feature] Support scrollable containers other than window

### ISSUE THREAD

**Issue by RangerDin** [catamphetamine/virtual-scroller#8]
Hi.

Thank you for this library.

It works great when the whole page scrolls.

Is it possible to use this library in dialogs? Or other components with scroll inside the body?

**Comment by catamphetamine** [comment]
I guess it would be possible.
But currently there's no such feature, and I won't need it in my apps.

**Comment by RangerDin** [comment]
Thank you for the quick answer.

**Comment by catamphetamine** [comment]
I'm reopening this issue because another man has asked about such feature.
I won't be implementing the feature though.
But if someone really wants they might try to implement something like that.
In that case:

* In all places where `getScrollY()` is called, it should be replaced with a function that returns `scrollY` inside the scrollable container rather than the `window`.
* In all places where `getScreenHeight()` is called, it should be replaced with a function that returns the scrollable container's height.
* Currently. the list listens to `window` `"resize"` event. If there'll be scrollable parents then I guess `ResizeObserver` (on modern browsers) could be used to track item visibility (not that this would be a realistic use case, but theoretically someone could resize one of such containers). Or maybe just handle the `"resize"` event as it's being done currently.

**Comment by ghost** [comment]
>  (not that this would be a realistic use case, but theoretically someone could resize one of such containers).

For example changing portrait mode to landscape mode on mobile phone where container takes 100% of screen width

**Comment by catamphetamine** [comment]
> For example changing portrait mode to landscape mode on mobile phone where container takes 100% of screen width

That would already be handled by `window` `"resize"` event listener.

**Comment by catamphetamine** [comment]
FYI: Released version `1.3.0` that adds *experimental* support for scrollable containers (`getScrollableContainer()` option).
Also, attached are some files showcasing common scenarios, including the scrollable container feature (`index-tbody-scrollableContainer.html`).
[bundle.zip](https://github.com/catamphetamine/virtual-scroller/files/4500458/bundle.zip)

**Comment by johman10** [comment]
Hey @catamphetamine! This is a great addition to your library and it makes it very close to being super useful for us. What I'm struggling with is how to use it with React if the `VirtualScroller` is a child of the `scrollableContainer`.

I made this to demonstrate my struggles: https://codesandbox.io/s/cocky-lumiere-7rdp1?file=/index.js.

Any help would be appreciated! :)

**Comment by catamphetamine** [comment]
@johman10 The issue was caused by `scrollableContainer` `ref` being set *after* `<VirtualScroller/>` has mounted, so by the time `<VirtualScroller/>` mounts (and initializes itself), `scrollableContainer` is `undefined`.
I changed the API a bit in the latest version (`1.4.x`): `getScrollableContainer()` option is replaced by `scrollableContainer` option.

```js
function Component() {
  const container = useRef()
  const [isMounted, setMounted] = useState()
  useEffect(() => {
    setMounted(true)
  }, [])
  return (
    <div ref={container}>
      {isMounted && 
        <VirtualScroller .../>
      }
    </div>
  )
}
```

**Comment by johman10** [comment]
@catamphetamine Thanks! That seems to work great!

For those interested I updated my example to work in the way he described: https://codesandbox.io/s/unruffled-framework-8pvsl?file=/index.js
